In [1]:
!pip install openai

Requirement already satisfied: openai in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (2.8.1)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (4.3.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (0.27.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (2.7.1)
Requirement already satisfied: sniffio in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (4.11.0)
Requirement already satisfied: idna>=2.8 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: certifi in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->openai) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.2 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.18.2)
Requirement already satisfied: colorama in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from tqdm>4->openai) (0.4.6)

[notice] A new release of pip is available: 24.1.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
from dotenv import load_dotenv
from openai import AsyncOpenAI
import pandas as pd
import re
import json
import asyncio

env_path = '.env'
load_dotenv(dotenv_path=env_path)

api_key = os.environ.get("OPENROUTER_API_KEY")

if not api_key:
    raise ValueError("OpenRouter API key not found. Please set OPENROUTER_API_KEY in your .env file.")

In [3]:
df = pd.read_csv("../scraper/final_dataset.csv")

df

,author,body_text,category,channel,error,link,published_date,scraped_at,title
0,Mikhael Gewati,KOMPAS.com- Dari hamparan pesisir timur hingga...,finance,ekbis,NaN,https://money.kompas.com/read/2025/11/22/09091...,"Kompas.com, 22 November 2025, 09:09 WIB",2025-11-22T16:54:39.469010,"Astra Bergerak Bersama Anak Bangsa, Membangun ..."
1,NaN,BANKIndonesia telah menurunkan suku bunga acua...,finance,ekbis,NaN,https://money.kompas.com/read/2025/11/22/08434...,"Kompas.com, 22 November 2025, 08:43 WIB",2025-11-22T16:54:37.215084,"Jeratan ""Special Rate"": Pasar Ganda Perbankan"
2,Nur Jamal Shaid,"JAKARTA, KOMPAS.com- Harga emas batangan yang ...",finance,ekbis,NaN,https://money.kompas.com/read/2025/11/22/07543...,"Kompas.com, Diperbarui 22/11/2025, 07:55 WIB",2025-11-22T16:54:36.424523,Harga Emas di Pegadaian 22 November 2025: Gale...
3,"Reni Susanti,","BANDUNG, KOMPAS.com– Vaksin HPV NusaGard, vaks...",finance,ekbis,NaN,https://money.kompas.com/read/2025/11/21/21373...,"Kompas.com, 21 November 2025, 21:37 WIB",2025-11-22T16:54:38.680471,Vaksin HPV Produksi Bio Farma Resmi Kantongi S...
4,Sakina Rakhma Diah Setiawan,"JAKARTA, KOMPAS.com -Iklim usaha yang sehat ti...",finance,ekbis,NaN,https://money.kompas.com/read/2025/11/21/21330...,"Kompas.com, 21 November 2025, 21:33 WIB",2025-11-22T16:54:42.749883,KPPU Soroti Tiga Area Risiko Pelanggaran dalam...
...,...,...,...,...,...,...,...,...,...
4013,Nafilah Sri Sagita K -detikHealth,Viral curhat wanita di TikTok sebagai pasangan...,berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Kamis, 20 Nov 2025 16:00 WIB",2025-11-22T13:08:38.505461,Viral Day 3 Nikah Berujung Masuk RS usai Honey...
4014,Sarah Oktaviani Alam -detikHealth,"Seorang YouTuber di Amerika Serikat, Andrew Fe...",berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Kamis, 20 Nov 2025 15:01 WIB",2025-11-22T13:08:39.834112,Youtuber Ikut Eksperimen 'Puasa' Sosmed 30 Har...
4015,"Dinda Islami, detikTV -detikHealth",Menko Pangan Zulhas ingin adanya penanda label...,detiktv,health,NaN,https://health.detik.com/detiktv/d-8220147/vid...,"Kamis, 20 Nov 2025 15:00 WIB",2025-11-22T13:08:41.200387,Video: Menko Pangan Mau Ada Label 'Tinggi Gula...
4016,Nafilah Sri Sagita K -detikHealth,"Nama Yasika Aulia Ramadhani, perempuan berusia...",berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Kamis, 20 Nov 2025 11:43 WIB",2025-11-22T13:08:42.562160,Kepala BGN soal Anak Waka DPRD Sulsel Punya 41...
4017,Nafilah Sri Sagita K -detikHealth,Pernyataan Wakil Ketua DPR RI Cucun Ahmad Syam...,berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Senin, 17 Nov 2025 18:00 WIB",2025-11-22T13:08:44.291381,Gaduh Komentar Wakil Ketua DPR Cucun soal Ahli...

In [17]:
df["body_text"] = df["body_text"].apply(
    lambda x: re.sub(r"^[^—–-]*[—–-]\s*", "", x)
)

# Jangan run code ini sebelum csv dibaca ulang

In [4]:
df

,author,body_text,category,channel,error,link,published_date,scraped_at,title
0,Mikhael Gewati,KOMPAS.com- Dari hamparan pesisir timur hingga...,finance,ekbis,NaN,https://money.kompas.com/read/2025/11/22/09091...,"Kompas.com, 22 November 2025, 09:09 WIB",2025-11-22T16:54:39.469010,"Astra Bergerak Bersama Anak Bangsa, Membangun ..."
1,NaN,BANKIndonesia telah menurunkan suku bunga acua...,finance,ekbis,NaN,https://money.kompas.com/read/2025/11/22/08434...,"Kompas.com, 22 November 2025, 08:43 WIB",2025-11-22T16:54:37.215084,"Jeratan ""Special Rate"": Pasar Ganda Perbankan"
2,Nur Jamal Shaid,"JAKARTA, KOMPAS.com- Harga emas batangan yang ...",finance,ekbis,NaN,https://money.kompas.com/read/2025/11/22/07543...,"Kompas.com, Diperbarui 22/11/2025, 07:55 WIB",2025-11-22T16:54:36.424523,Harga Emas di Pegadaian 22 November 2025: Gale...
3,"Reni Susanti,","BANDUNG, KOMPAS.com– Vaksin HPV NusaGard, vaks...",finance,ekbis,NaN,https://money.kompas.com/read/2025/11/21/21373...,"Kompas.com, 21 November 2025, 21:37 WIB",2025-11-22T16:54:38.680471,Vaksin HPV Produksi Bio Farma Resmi Kantongi S...
4,Sakina Rakhma Diah Setiawan,"JAKARTA, KOMPAS.com -Iklim usaha yang sehat ti...",finance,ekbis,NaN,https://money.kompas.com/read/2025/11/21/21330...,"Kompas.com, 21 November 2025, 21:33 WIB",2025-11-22T16:54:42.749883,KPPU Soroti Tiga Area Risiko Pelanggaran dalam...
...,...,...,...,...,...,...,...,...,...
4013,Nafilah Sri Sagita K -detikHealth,Viral curhat wanita di TikTok sebagai pasangan...,berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Kamis, 20 Nov 2025 16:00 WIB",2025-11-22T13:08:38.505461,Viral Day 3 Nikah Berujung Masuk RS usai Honey...
4014,Sarah Oktaviani Alam -detikHealth,"Seorang YouTuber di Amerika Serikat, Andrew Fe...",berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Kamis, 20 Nov 2025 15:01 WIB",2025-11-22T13:08:39.834112,Youtuber Ikut Eksperimen 'Puasa' Sosmed 30 Har...
4015,"Dinda Islami, detikTV -detikHealth",Menko Pangan Zulhas ingin adanya penanda label...,detiktv,health,NaN,https://health.detik.com/detiktv/d-8220147/vid...,"Kamis, 20 Nov 2025 15:00 WIB",2025-11-22T13:08:41.200387,Video: Menko Pangan Mau Ada Label 'Tinggi Gula...
4016,Nafilah Sri Sagita K -detikHealth,"Nama Yasika Aulia Ramadhani, perempuan berusia...",berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Kamis, 20 Nov 2025 11:43 WIB",2025-11-22T13:08:42.562160,Kepala BGN soal Anak Waka DPRD Sulsel Punya 41...
4017,Nafilah Sri Sagita K -detikHealth,Pernyataan Wakil Ketua DPR RI Cucun Ahmad Syam...,berita-detikhealth,health,NaN,https://health.detik.com/berita-detikhealth/d-...,"Senin, 17 Nov 2025 18:00 WIB",2025-11-22T13:08:44.291381,Gaduh Komentar Wakil Ketua DPR Cucun soal Ahli...

In [5]:
client = AsyncOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
    default_headers={"HTTP-Referer": "http://localhost:5000"}
)

In [6]:
ner_prompts = '''Here is a paragraph. Please extract all the named entities in the paragraph with the following format: [{{"entity": Entity Name 1, "type": Entity Type 1}}, {{"entity": Entity Name 2, "type": Entity Type 2}}, ...].

Only extract entities that match these types:
- CRD: Cardinal (numbers that don't fall into other categories)
- DAT: Date (specific dates, days, months, years)
- EVT: Event (named events like conferences, wars, sports events)
- FAC: Facility (buildings, airports, highways, bridges)
- GPE: Geopolitical Entity (countries, cities, states)
- LAW: Law Entity (laws, legal documents, like Undang-Undang)
- LOC: Location (non-GPE locations, mountain ranges, bodies of water)
- MON: Money (monetary values)
- NOR: Political Organization (political parties, movements)
- ORD: Ordinal (first, second, third, etc.)
- ORG: Organization (companies, agencies, institutions)
- PER: Person (people, including fictional)
- PRC: Percent (percentage values)
- PRD: Product (objects, vehicles, foods, etc., not services)
- QTY: Quantity (measurements, weights, distances)
- REG: Religion (religions, religious groups)
- TIM: Time (times smaller than a day)
- WOA: Work of Art (titles of books, songs, paintings)
- LAN: Language (named languages)

Paragraph: {para}

Named Entities (JSON format only):''' 
summary_prompts = "Here is a paragraph. Please give a summary of the paragraph. \n\nParagraph: {para}\n\n Summary: "

In [7]:
user_prompts = df['body_text']
system_prompt = "You are the smartest AI assistant"

In [8]:
processed_ner_prompts = []
processed_summary_prompts = []

for i in user_prompts:
    processed_ner_prompts.append(ner_prompts.format(para=i))
    processed_summary_prompts.append(summary_prompts.format(para=i))

In [9]:
ner_res = []
summary_res = []

In [10]:
sema = asyncio.Semaphore(10)

In [11]:
async def run_prompt(processed_prompt, idx, status):
    async with sema:
        print(idx, status)
        
        final_prompt = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": processed_prompt}
        ]

        response = await client.chat.completions.create(
            model="qwen/qwen3-30b-a3b-instruct-2507",
            messages=final_prompt
        )

        return {
            "prompt": processed_prompt,
            "answer": response.choices[0].message.content
        }

In [12]:
async def run_ner_prompts():
    tasks = [run_prompt(p, i, 'ner') for i, p in enumerate(processed_ner_prompts)]
    results = await asyncio.gather(*tasks)
    return results

async def run_summary_prompts():
    tasks = [run_prompt(p, i, 'summary') for i, p in enumerate(processed_summary_prompts)]
    results = await asyncio.gather(*tasks)
    return results

async def main():
    results = await asyncio.gather(
        run_ner_prompts(),
        # run_summary_prompts()
    )
    return results

In [13]:
res = await main()

0 ner
1 ner
2 ner
3 ner
4 ner
5 ner
6 ner
7 ner
8 ner
9 ner
10 ner
11 ner
12 ner
13 ner
14 ner
15 ner
16 ner
17 ner
18 ner
19 ner
20 ner
21 ner
22 ner
23 ner
24 ner
25 ner
26 ner
27 ner
28 ner
29 ner
30 ner
31 ner
32 ner
33 ner
34 ner
35 ner
36 ner
37 ner
38 ner
39 ner
40 ner
41 ner
42 ner
43 ner
44 ner
45 ner
46 ner
47 ner
48 ner
49 ner
50 ner
51 ner
52 ner
53 ner
54 ner
55 ner
56 ner
57 ner
58 ner
59 ner
60 ner
61 ner
62 ner
63 ner
64 ner
65 ner
66 ner
67 ner
68 ner
69 ner
70 ner
71 ner
72 ner
73 ner
74 ner
75 ner
76 ner
77 ner
78 ner
79 ner
80 ner
81 ner
82 ner
83 ner
84 ner
85 ner
86 ner
87 ner
88 ner
89 ner
90 ner
91 ner
92 ner
93 ner
94 ner
95 ner
96 ner
97 ner
98 ner
99 ner
100 ner
101 ner
102 ner
103 ner
104 ner
105 ner
106 ner
107 ner
108 ner
109 ner
110 ner
111 ner
112 ner
113 ner
114 ner
115 ner
116 ner
117 ner
118 ner
119 ner
120 ner
121 ner
122 ner
123 ner
124 ner
125 ner
126 ner
127 ner
128 ner
129 ner
130 ner
131 ner
132 ner
133 ner
134 ner
135 ner
136 ner
137 ner
138 ner
139 ner
140 ner
141 ner
142 ner
143 ner
144 ner
145 ner
146 ner
147 ner
148 ner
149 ner
150 ner
151 ner
152 ner
153 ner
154 ner
155 ner
156 ner
157 ner
158 ner
159 ner
160 ner
161 ner
162 ner
163 ner
164 ner
165 ner
166 ner
167 ner
168 ner
169 ner
170 ner
171 ner
172 ner
173 ner
174 ner
175 ner
176 ner
177 ner
178 ner
179 ner
180 ner
181 ner
182 ner
183 ner
184 ner
185 ner
186 ner
187 ner
188 ner
189 ner
190 ner
191 ner
192 ner
193 ner
194 ner
195 ner
196 ner
197 ner
198 ner
199 ner
200 ner
201 ner
202 ner
203 ner
204 ner
205 ner
206 ner
207 ner
208 ner
209 ner
210 ner
211 ner
212 ner
213 ner
214 ner
215 ner
216 ner
217 ner
218 ner
219 ner
220 ner
221 ner
222 ner
223 ner
224 ner
225 ner
226 ner
227 ner
228 ner
229 ner
230 ner
231 ner
232 ner
233 ner
234 ner
235 ner
236 ner
237 ner
238 ner
239 ner
240 ner
241 ner
242 ner
243 ner
244 ner
245 ner
246 ner
247 ner
248 ner
249 ner
250 ner
251 ner
252 ner
253 ner
254 ner
255 ner
256 ner
257 ner
258 ner
259 ner
260 ner
261 ner
262 ner
263 ner
264 ner
265 ner
266 ner
267 ner
268 ner
269 ner
270 ner
271 ner
272 ner
273 ner
274 ner
275 ner
276 ner
277 ner
278 ner
279 ner
280 ner
281 ner
282 ner
283 ner
284 ner
285 ner
286 ner
287 ner
288 ner
289 ner
290 ner
291 ner
292 ner
293 ner
294 ner
295 ner
296 ner
297 ner
298 ner
299 ner
300 ner
301 ner
302 ner
303 ner
304 ner
305 ner
306 ner
307 ner
308 ner
309 ner
310 ner
311 ner
312 ner
313 ner
314 ner
315 ner
316 ner
317 ner
318 ner
319 ner
320 ner
321 ner
322 ner
323 ner
324 ner
325 ner
326 ner
327 ner
328 ner
329 ner
330 ner
331 ner
332 ner
333 ner
334 ner
335 ner
336 ner
337 ner
338 ner
339 ner
340 ner
341 ner
342 ner
343 ner
344 ner
345 ner
346 ner
347 ner
348 ner
349 ner
350 ner
351 ner
352 ner
353 ner
354 ner
355 ner
356 ner
357 ner
358 ner
359 ner
360 ner
361 ner
362 ner
363 ner
364 ner
365 ner
366 ner
367 ner
368 ner
369 ner
370 ner
371 ner
372 ner
373 ner
374 ner
375 ner
376 ner
377 ner
378 ner
379 ner
380 ner
381 ner
382 ner
383 ner
384 ner
385 ner
386 ner
387 ner
388 ner
389 ner
390 ner
391 ner
392 ner
393 ner
394 ner
395 ner
396 ner
397 ner
398 ner
399 ner
400 ner
401 ner
402 ner
403 ner
404 ner
405 ner
406 ner
407 ner
408 ner
409 ner
410 ner
411 ner
412 ner
413 ner
414 ner
415 ner
416 ner
417 ner
418 ner
419 ner
420 ner
421 ner
422 ner
423 ner
424 ner
425 ner
426 ner
427 ner
428 ner
429 ner
430 ner
431 ner
432 ner
433 ner
434 ner
435 ner
436 ner
437 ner
438 ner
439 ner
440 ner
441 ner
442 ner
443 ner
444 ner
445 ner
446 ner
447 ner
448 ner
449 ner
450 ner
451 ner
452 ner
453 ner
454 ner
455 ner
456 ner
457 ner
458 ner
459 ner
460 ner
461 ner
462 ner
463 ner
464 ner
465 ner
466 ner
467 ner
468 ner
469 ner
470 ner
471 ner
472 ner
473 ner
474 ner
475 ner
476 ner
477 ner
478 ner
479 ner
480 ner
481 ner
482 ner
483 ner
484 ner
485 ner
486 ner
487 ner
488 ner
489 ner
490 ner
491 ner
492 ner
493 ner
494 ner
495 ner
496 ner
497 ner
498 ner
499 ner
500 ner
501 ner
502 ner
503 ner
504 ner
505 ner
506 ner
507 ner
508 ner
509 ner
510 ner
511 ner
512 ner
513 ner
514 ner
515 ner
516 ner
517 ner
518 ner
519 ner
520 ner
521 ner
522 ner
523 ner
524 ner
525 ner
526 ner
527 ner
528 ner
529 ner
530 ner
531 ner
532 ner
533 ner
534 ner
535 ner
536 ner
537 ner
538 ner
539 ner
540 ner
541 ner
542 ner
543 ner
544 ner
545 ner
546 ner
547 ner
548 ner
549 ner
550 ner
551 ner
552 ner
553 ner
554 ner
555 ner
556 ner
557 ner
558 ner
559 ner
560 ner
561 ner
562 ner
563 ner
564 ner
565 ner
566 ner
567 ner
568 ner
569 ner
570 ner
571 ner
572 ner
573 ner
574 ner
575 ner
576 ner
577 ner
578 ner
579 ner
580 ner
581 ner
582 ner
583 ner
584 ner
585 ner
586 ner
587 ner
588 ner
589 ner
590 ner
591 ner
592 ner
593 ner
594 ner
595 ner
596 ner
597 ner
598 ner
599 ner
600 ner
601 ner
602 ner
603 ner
604 ner
605 ner
606 ner
607 ner
608 ner
609 ner
610 ner
611 ner
612 ner
613 ner
614 ner
615 ner
616 ner
617 ner
618 ner
619 ner
620 ner
621 ner
622 ner
623 ner
624 ner
625 ner
626 ner
627 ner
628 ner
629 ner
630 ner
631 ner
632 ner
633 ner
634 ner
635 ner
636 ner
637 ner
638 ner
639 ner
640 ner
641 ner
642 ner
643 ner
644 ner
645 ner
646 ner
647 ner
648 ner
649 ner
650 ner
651 ner
652 ner
653 ner
654 ner
655 ner
656 ner
657 ner
658 ner
659 ner
660 ner
661 ner
662 ner
663 ner
664 ner
665 ner
666 ner
667 ner
668 ner
669 ner
670 ner
671 ner
672 ner
673 ner
674 ner
675 ner
676 ner
677 ner
678 ner
679 ner
680 ner
681 ner
682 ner
683 ner
684 ner
685 ner
686 ner
687 ner
688 ner
689 ner
690 ner
691 ner
692 ner
693 ner
694 ner
695 ner
696 ner
697 ner
698 ner
699 ner
700 ner
701 ner
702 ner
703 ner
704 ner
705 ner
706 ner
707 ner
708 ner
709 ner
710 ner
711 ner
712 ner
713 ner
714 ner
715 ner
716 ner
717 ner
718 ner
719 ner
720 ner
721 ner
722 ner
723 ner
724 ner
725 ner
726 ner
727 ner
728 ner
729 ner
730 ner
731 ner
732 ner
733 ner
734 ner
735 ner
736 ner
737 ner
738 ner
739 ner
740 ner
741 ner
742 ner
743 ner
744 ner
745 ner
746 ner
747 ner
748 ner
749 ner
750 ner
751 ner
752 ner
753 ner
754 ner
755 ner
756 ner
757 ner
758 ner
759 ner
760 ner
761 ner
762 ner
763 ner
764 ner
765 ner
766 ner
767 ner
768 ner
769 ner
770 ner
771 ner
772 ner
773 ner
774 ner
775 ner
776 ner
777 ner
778 ner
779 ner
780 ner
781 ner
782 ner
783 ner
784 ner
785 ner
786 ner
787 ner
788 ner
789 ner
790 ner
791 ner
792 ner
793 ner
794 ner
795 ner
796 ner
797 ner
798 ner
799 ner
800 ner
801 ner
802 ner
803 ner
804 ner
805 ner
806 ner
807 ner
808 ner
809 ner
810 ner
811 ner
812 ner
813 ner
814 ner
815 ner
816 ner
817 ner
818 ner
819 ner
820 ner
821 ner
822 ner
823 ner
824 ner
825 ner
826 ner
827 ner
828 ner
829 ner
830 ner
831 ner
832 ner
833 ner
834 ner
835 ner
836 ner
837 ner
838 ner
839 ner
840 ner
841 ner
842 ner
843 ner
844 ner
845 ner
846 ner
847 ner
848 ner
849 ner
850 ner
851 ner
852 ner
853 ner
854 ner
855 ner
856 ner
857 ner
858 ner
859 ner
860 ner
861 ner
862 ner
863 ner
864 ner
865 ner
866 ner
867 ner
868 ner
869 ner
870 ner
871 ner
872 ner
873 ner
874 ner
875 ner
876 ner
877 ner
878 ner
879 ner
880 ner
881 ner
882 ner
883 ner
884 ner
885 ner
886 ner
887 ner
888 ner
889 ner
890 ner
891 ner
892 ner
893 ner
894 ner
895 ner
896 ner
897 ner
898 ner
899 ner
900 ner
901 ner
902 ner
903 ner
904 ner
905 ner
906 ner
907 ner
908 ner
909 ner
910 ner
911 ner
912 ner
913 ner
914 ner
915 ner
916 ner
917 ner
918 ner
919 ner
920 ner
921 ner
922 ner
923 ner
924 ner
925 ner
926 ner
927 ner
928 ner
929 ner
930 ner
931 ner
932 ner
933 ner
934 ner
935 ner
936 ner
937 ner
938 ner
939 ner
940 ner
941 ner
942 ner
943 ner
944 ner
945 ner
946 ner
947 ner
948 ner
949 ner
950 ner
951 ner
952 ner
953 ner
954 ner
955 ner
956 ner
957 ner
958 ner
959 ner
960 ner
961 ner
962 ner
963 ner
964 ner
965 ner
966 ner
967 ner
968 ner
969 ner
970 ner
971 ner
972 ner
973 ner
974 ner
975 ner
976 ner
977 ner
978 ner
979 ner
980 ner
981 ner
982 ner
983 ner
984 ner
985 ner
986 ner
987 ner
988 ner
989 ner
990 ner
991 ner
992 ner
993 ner
994 ner
995 ner
996 ner
997 ner
998 ner
999 ner
1000 ner
1001 ner
1002 ner
1003 ner
1004 ner
1005 ner
1006 ner
1007 ner
1008 ner
1009 ner
1010 ner
1011 ner
1012 ner
1013 ner
1014 ner
1015 ner
1016 ner
1017 ner
1018 ner
1019 ner
1020 ner
1021 ner
1022 ner
1023 ner
1024 ner
1025 ner
1026 ner
1027 ner
1028 ner
1029 ner
1030 ner
1031 ner
1032 ner
1033 ner
1034 ner
1035 ner
1036 ner
1037 ner
1038 ner
1039 ner
1040 ner
1041 ner
1042 ner
1043 ner
1044 ner
1045 ner
1046 ner
1047 ner
1048 ner
1049 ner
1050 ner
1051 ner
1052 ner
1053 ner
1054 ner
1055 ner
1056 ner
1057 ner
1058 ner
1059 ner
1060 ner
1061 ner
1062 ner
1063 ner
1064 ner
1065 ner
1066 ner
1067 ner
1068 ner
1069 ner
1070 ner
1071 ner
1072 ner
1073 ner
1074 ner
1075 ner
1076 ner
1077 ner
1078 ner
1079 ner
1080 ner
1081 ner
1082 ner
1083 ner
1084 ner
1085 ner
1086 ner
1087 ner
1088 ner
1089 ner
1090 ner
1091 ner
1092 ner
1093 ner
1094 ner
1095 ner
1096 ner
1097 ner
1098 ner
1099 ner
1100 ner
1101 ner
1102 ner
1103 ner
1104 ner
1105 ner
1106 ner
1107 ner
1108 ner
1109 ner
1110 ner
1111 ner
1112 ner
1113 ner
1114 ner
1115 ner
1116 ner
1117 ner
1118 ner
1119 ner
1120 ner
1121 ner
1122 ner
1123 ner
1124 ner
1125 ner
1126 ner
1127 ner
1128 ner
1129 ner
1130 ner
1131 ner
1132 ner
1133 ner
1134 ner
1135 ner
1136 ner
1137 ner
1138 ner
1139 ner
1140 ner
1141 ner
1142 ner
1143 ner
1144 ner
1145 ner
1146 ner
1147 ner
1148 ner
1149 ner
1150 ner
1151 ner
1152 ner
1153 ner
1154 ner
1155 ner
1156 ner
1157 ner
1158 ner
1159 ner
1160 ner
1161 ner
1162 ner
1163 ner
1164 ner
1165 ner
1166 ner
1167 ner
1168 ner
1169 ner
1170 ner
1171 ner
1172 ner
1173 ner
1174 ner
1175 ner
1176 ner
1177 ner
1178 ner
1179 ner
1180 ner
1181 ner
1182 ner
1183 ner
1184 ner
1185 ner
1186 ner
1187 ner
1188 ner
1189 ner
1190 ner
1191 ner
1192 ner
1193 ner
1194 ner
1195 ner
1196 ner
1197 ner
1198 ner
1199 ner
1200 ner
1201 ner
1202 ner
1203 ner
1204 ner
1205 ner
1206 ner
1207 ner
1208 ner
1209 ner
1210 ner
1211 ner
1212 ner
1213 ner
1214 ner
1215 ner
1216 ner
1217 ner
1218 ner
1219 ner
1220 ner
1221 ner
1222 ner
1223 ner
1224 ner
1225 ner
1226 ner
1227 ner
1228 ner
1229 ner
1230 ner
1231 ner
1232 ner
1233 ner
1234 ner
1235 ner
1236 ner
1237 ner
1238 ner
1239 ner
1240 ner
1241 ner
1242 ner
1243 ner
1244 ner
1245 ner
1246 ner
1247 ner
1248 ner
1249 ner
1250 ner
1251 ner
1252 ner
1253 ner
1254 ner
1255 ner
1256 ner
1257 ner
1258 ner
1259 ner
1260 ner
1261 ner
1262 ner
1263 ner
1264 ner
1265 ner
1266 ner
1267 ner
1268 ner
1269 ner
1270 ner
1271 ner
1272 ner
1273 ner
1274 ner
1275 ner
1276 ner
1277 ner
1278 ner
1279 ner
1280 ner
1281 ner
1282 ner
1283 ner
1284 ner
1285 ner
1286 ner
1287 ner
1288 ner
1289 ner
1290 ner
1291 ner
1292 ner
1293 ner
1294 ner
1295 ner
1296 ner
1297 ner
1298 ner
1299 ner
1300 ner
1301 ner
1302 ner
1303 ner
1304 ner
1305 ner
1306 ner
1307 ner
1308 ner
1309 ner
1310 ner
1311 ner
1312 ner
1313 ner
1314 ner
1315 ner
1316 ner
1317 ner
1318 ner
1319 ner
1320 ner
1321 ner
1322 ner
1323 ner
1324 ner
1325 ner
1326 ner
1327 ner
1328 ner
1329 ner
1330 ner
1331 ner
1332 ner
1333 ner
1334 ner
1335 ner
1336 ner
1337 ner
1338 ner
1339 ner
1340 ner
1341 ner
1342 ner
1343 ner
1344 ner
1345 ner
1346 ner
1347 ner
1348 ner
1349 ner
1350 ner
1351 ner
1352 ner
1353 ner
1354 ner
1355 ner
1356 ner
1357 ner
1358 ner
1359 ner
1360 ner
1361 ner
1362 ner
1363 ner
1364 ner
1365 ner
1366 ner
1367 ner
1368 ner
1369 ner
1370 ner
1371 ner
1372 ner
1373 ner
1374 ner
1375 ner
1376 ner
1377 ner
1378 ner
1379 ner
1380 ner
1381 ner
1382 ner
1383 ner
1384 ner
1385 ner
1386 ner
1387 ner
1388 ner
1389 ner
1390 ner
1391 ner
1392 ner
1393 ner
1394 ner
1395 ner
1396 ner
1397 ner
1398 ner
1399 ner
1400 ner
1401 ner
1402 ner
1403 ner
1404 ner
1405 ner
1406 ner
1407 ner
1408 ner
1409 ner
1410 ner
1411 ner
1412 ner
1413 ner
1414 ner
1415 ner
1416 ner
1417 ner
1418 ner
1419 ner
1420 ner
1421 ner
1422 ner
1423 ner
1424 ner
1425 ner
1426 ner
1427 ner
1428 ner
1429 ner
1430 ner
1431 ner
1432 ner
1433 ner
1434 ner
1435 ner
1436 ner
1437 ner
1438 ner
1439 ner
1440 ner
1441 ner
1442 ner
1443 ner
1444 ner
1445 ner
1446 ner
1447 ner
1448 ner
1449 ner
1450 ner
1451 ner
1452 ner
1453 ner
1454 ner
1455 ner
1456 ner
1457 ner
1458 ner
1459 ner
1460 ner
1461 ner
1462 ner
1463 ner
1464 ner
1465 ner
1466 ner
1467 ner
1468 ner
1469 ner
1470 ner
1471 ner
1472 ner
1473 ner
1474 ner
1475 ner
1476 ner
1477 ner
1478 ner
1479 ner
1480 ner
1481 ner
1482 ner
1483 ner
1484 ner
1485 ner
1486 ner
1487 ner
1488 ner
1489 ner
1490 ner
1491 ner
1492 ner
1493 ner
1494 ner
1495 ner
1496 ner
1497 ner
1498 ner
1499 ner
1500 ner
1501 ner
1502 ner
1503 ner
1504 ner
1505 ner
1506 ner
1507 ner
1508 ner
1509 ner
1510 ner
1511 ner
1512 ner
1513 ner
1514 ner
1515 ner
1516 ner
1517 ner
1518 ner
1519 ner
1520 ner
1521 ner
1522 ner
1523 ner
1524 ner
1525 ner
1526 ner
1527 ner
1528 ner
1529 ner
1530 ner
1531 ner
1532 ner
1533 ner
1534 ner
1535 ner
1536 ner
1537 ner
1538 ner
1539 ner
1540 ner
1541 ner
1542 ner
1543 ner
1544 ner
1545 ner
1546 ner
1547 ner
1548 ner
1549 ner
1550 ner
1551 ner
1552 ner
1553 ner
1554 ner
1555 ner
1556 ner
1557 ner
1558 ner
1559 ner
1560 ner
1561 ner
1562 ner
1563 ner
1564 ner
1565 ner
1566 ner
1567 ner
1568 ner
1569 ner
1570 ner
1571 ner
1572 ner
1573 ner
1574 ner
1575 ner
1576 ner
1577 ner
1578 ner
1579 ner
1580 ner
1581 ner
1582 ner
1583 ner
1584 ner
1585 ner
1586 ner
1587 ner
1588 ner
1589 ner
1590 ner
1591 ner
1592 ner
1593 ner
1594 ner
1595 ner
1596 ner
1597 ner
1598 ner
1599 ner
1600 ner
1601 ner
1602 ner
1603 ner
1604 ner
1605 ner
1606 ner
1607 ner
1608 ner
1609 ner
1610 ner
1611 ner
1612 ner
1613 ner
1614 ner
1615 ner
1616 ner
1617 ner
1618 ner
1619 ner
1620 ner
1621 ner
1622 ner
1623 ner
1624 ner
1625 ner
1626 ner
1627 ner
1628 ner
1629 ner
1630 ner
1631 ner
1632 ner
1633 ner
1634 ner
1635 ner
1636 ner
1637 ner
1638 ner
1639 ner
1640 ner
1641 ner
1642 ner
1643 ner
1644 ner
1645 ner
1646 ner
1647 ner
1648 ner
1649 ner
1650 ner
1651 ner
1652 ner
1653 ner
1654 ner
1655 ner
1656 ner
1657 ner
1658 ner
1659 ner
1660 ner
1661 ner
1662 ner
1663 ner
1664 ner
1665 ner
1666 ner
1667 ner
1668 ner
1669 ner
1670 ner
1671 ner
1672 ner
1673 ner
1674 ner
1675 ner
1676 ner
1677 ner
1678 ner
1679 ner
1680 ner
1681 ner
1682 ner
1683 ner
1684 ner
1685 ner
1686 ner
1687 ner
1688 ner
1689 ner
1690 ner
1691 ner
1692 ner
1693 ner
1694 ner
1695 ner
1696 ner
1697 ner
1698 ner
1699 ner
1700 ner
1701 ner
1702 ner
1703 ner
1704 ner
1705 ner
1706 ner
1707 ner
1708 ner
1709 ner
1710 ner
1711 ner
1712 ner
1713 ner
1714 ner
1715 ner
1716 ner
1717 ner
1718 ner
1719 ner
1720 ner
1721 ner
1722 ner
1723 ner
1724 ner
1725 ner
1726 ner
1727 ner
1728 ner
1729 ner
1730 ner
1731 ner
1732 ner
1733 ner
1734 ner
1735 ner
1736 ner
1737 ner
1738 ner
1739 ner
1740 ner
1741 ner
1742 ner
1743 ner
1744 ner
1745 ner
1746 ner
1747 ner
1748 ner
1749 ner
1750 ner
1751 ner
1752 ner
1753 ner
1754 ner
1755 ner
1756 ner
1757 ner
1758 ner
1759 ner
1760 ner
1761 ner
1762 ner
1763 ner
1764 ner
1765 ner
1766 ner
1767 ner
1768 ner
1769 ner
1770 ner
1771 ner
1772 ner
1773 ner
1774 ner
1775 ner
1776 ner
1777 ner
1778 ner
1779 ner
1780 ner
1781 ner
1782 ner
1783 ner
1784 ner
1785 ner
1786 ner
1787 ner
1788 ner
1789 ner
1790 ner
1791 ner
1792 ner
1793 ner
1794 ner
1795 ner
1796 ner
1797 ner
1798 ner
1799 ner
1800 ner
1801 ner
1802 ner
1803 ner
1804 ner
1805 ner
1806 ner
1807 ner
1808 ner
1809 ner
1810 ner
1811 ner
1812 ner
1813 ner
1814 ner
1815 ner
1816 ner
1817 ner
1818 ner
1819 ner
1820 ner
1821 ner
1822 ner
1823 ner
1824 ner
1825 ner
1826 ner
1827 ner
1828 ner
1829 ner
1830 ner
1831 ner
1832 ner
1833 ner
1834 ner
1835 ner
1836 ner
1837 ner
1838 ner
1839 ner
1840 ner
1841 ner
1842 ner
1843 ner
1844 ner
1845 ner
1846 ner
1847 ner
1848 ner
1849 ner
1850 ner
1851 ner
1852 ner
1853 ner
1854 ner
1855 ner
1856 ner
1857 ner
1858 ner
1859 ner
1860 ner
1861 ner
1862 ner
1863 ner
1864 ner
1865 ner
1866 ner
1867 ner
1868 ner
1869 ner
1870 ner
1871 ner
1872 ner
1873 ner
1874 ner
1875 ner
1876 ner
1877 ner
1878 ner
1879 ner
1880 ner
1881 ner
1882 ner
1883 ner
1884 ner
1885 ner
1886 ner
1887 ner
1888 ner
1889 ner
1890 ner
1891 ner
1892 ner
1893 ner
1894 ner
1895 ner
1896 ner
1897 ner
1898 ner
1899 ner
1900 ner
1901 ner
1902 ner
1903 ner
1904 ner
1905 ner
1906 ner
1907 ner
1908 ner
1909 ner
1910 ner
1911 ner
1912 ner
1913 ner
1914 ner
1915 ner
1916 ner
1917 ner
1918 ner
1919 ner
1920 ner
1921 ner
1922 ner
1923 ner
1924 ner
1925 ner
1926 ner
1927 ner
1928 ner
1929 ner
1930 ner
1931 ner
1932 ner
1933 ner
1934 ner
1935 ner
1936 ner
1937 ner
1938 ner
1939 ner
1940 ner
1941 ner
1942 ner
1943 ner
1944 ner
1945 ner
1946 ner
1947 ner
1948 ner
1949 ner
1950 ner
1951 ner
1952 ner
1953 ner
1954 ner
1955 ner
1956 ner
1957 ner
1958 ner
1959 ner
1960 ner
1961 ner
1962 ner
1963 ner
1964 ner
1965 ner
1966 ner
1967 ner
1968 ner
1969 ner
1970 ner
1971 ner
1972 ner
1973 ner
1974 ner
1975 ner
1976 ner
1977 ner
1978 ner
1979 ner
1980 ner
1981 ner
1982 ner
1983 ner
1984 ner
1985 ner
1986 ner
1987 ner
1988 ner
1989 ner
1990 ner
1991 ner
1992 ner
1993 ner
1994 ner
1995 ner
1996 ner
1997 ner
1998 ner
1999 ner
2000 ner
2001 ner
2002 ner
2003 ner
2004 ner
2005 ner
2006 ner
2007 ner
2008 ner
2009 ner
2010 ner
2011 ner
2012 ner
2013 ner
2014 ner
2015 ner
2016 ner
2017 ner
2018 ner
2019 ner
2020 ner
2021 ner
2022 ner
2023 ner
2024 ner
2025 ner
2026 ner
2027 ner
2028 ner
2029 ner
2030 ner
2031 ner
2032 ner
2033 ner
2034 ner
2035 ner
2036 ner
2037 ner
2038 ner
2039 ner
2040 ner
2041 ner
2042 ner
2043 ner
2044 ner
2045 ner
2046 ner
2047 ner
2048 ner
2049 ner
2050 ner
2051 ner
2052 ner
2053 ner
2054 ner
2055 ner
2056 ner
2057 ner
2058 ner
2059 ner
2060 ner
2061 ner
2062 ner
2063 ner
2064 ner
2065 ner
2066 ner
2067 ner
2068 ner
2069 ner
2070 ner
2071 ner
2072 ner
2073 ner
2074 ner
2075 ner
2076 ner
2077 ner
2078 ner
2079 ner
2080 ner
2081 ner
2082 ner
2083 ner
2084 ner
2085 ner
2086 ner
2087 ner
2088 ner
2089 ner
2090 ner
2091 ner
2092 ner
2093 ner
2094 ner
2095 ner
2096 ner
2097 ner
2098 ner
2099 ner
2100 ner
2101 ner
2102 ner
2103 ner
2104 ner
2105 ner
2106 ner
2107 ner
2108 ner
2109 ner
2110 ner
2111 ner
2112 ner
2113 ner
2114 ner
2115 ner
2116 ner
2117 ner
2118 ner
2119 ner
2120 ner
2121 ner
2122 ner
2123 ner
2124 ner
2125 ner
2126 ner
2127 ner
2128 ner
2129 ner
2130 ner
2131 ner
2132 ner
2133 ner
2134 ner
2135 ner
2136 ner
2137 ner
2138 ner
2139 ner
2140 ner
2141 ner
2142 ner
2143 ner
2144 ner
2145 ner
2146 ner
2147 ner
2148 ner
2149 ner
2150 ner
2151 ner
2152 ner
2153 ner
2154 ner
2155 ner
2156 ner
2157 ner
2158 ner
2159 ner
2160 ner
2161 ner
2162 ner
2163 ner
2164 ner
2165 ner
2166 ner
2167 ner
2168 ner
2169 ner
2170 ner
2171 ner
2172 ner
2173 ner
2174 ner
2175 ner
2176 ner
2177 ner
2178 ner
2179 ner
2180 ner
2181 ner
2182 ner
2183 ner
2184 ner
2185 ner
2186 ner
2187 ner
2188 ner
2189 ner
2190 ner
2191 ner
2192 ner
2193 ner
2194 ner
2195 ner
2196 ner
2197 ner
2198 ner
2199 ner
2200 ner
2201 ner
2202 ner
2203 ner
2204 ner
2205 ner
2206 ner
2207 ner
2208 ner
2209 ner
2210 ner
2211 ner
2212 ner
2213 ner
2214 ner
2215 ner
2216 ner
2217 ner
2218 ner
2219 ner
2220 ner
2221 ner
2222 ner
2223 ner
2224 ner
2225 ner
2226 ner
2227 ner
2228 ner
2229 ner
2230 ner
2231 ner
2232 ner
2233 ner
2234 ner
2235 ner
2236 ner
2237 ner
2238 ner
2239 ner
2240 ner
2241 ner
2242 ner
2243 ner
2244 ner
2245 ner
2246 ner
2247 ner
2248 ner
2249 ner
2250 ner
2251 ner
2252 ner
2253 ner
2254 ner
2255 ner
2256 ner
2257 ner
2258 ner
2259 ner
2260 ner
2261 ner
2262 ner
2263 ner
2264 ner
2265 ner
2266 ner
2267 ner
2268 ner
2269 ner
2270 ner
2271 ner
2272 ner
2273 ner
2274 ner
2275 ner
2276 ner
2277 ner
2278 ner
2279 ner
2280 ner
2281 ner
2282 ner
2283 ner
2284 ner
2285 ner
2286 ner
2287 ner
2288 ner
2289 ner
2290 ner
2291 ner
2292 ner
2293 ner
2294 ner
2295 ner
2296 ner
2297 ner
2298 ner
2299 ner
2300 ner
2301 ner
2302 ner
2303 ner
2304 ner
2305 ner
2306 ner
2307 ner
2308 ner
2309 ner
2310 ner
2311 ner
2312 ner
2313 ner
2314 ner
2315 ner
2316 ner
2317 ner
2318 ner
2319 ner
2320 ner
2321 ner
2322 ner
2323 ner
2324 ner
2325 ner
2326 ner
2327 ner
2328 ner
2329 ner
2330 ner
2331 ner
2332 ner
2333 ner
2334 ner
2335 ner
2336 ner
2337 ner
2338 ner
2339 ner
2340 ner
2341 ner
2342 ner
2343 ner
2344 ner

In [14]:
files_length = len(os.listdir())

with open(f"{files_length}.json", "w") as f:
    json.dump(res, f, indent=2)